--- !ruby/object:VR_ENV
vr_yaml_file: "/home/sci/visualruby/saski/.vr_settings.yaml"
width: 1366
height: 705
panel_pos: 238
notebook_panel_position: 529
run_command_line: ruby main.rb
open_files:
- "/home/sci/visualruby/saski/main.rb"
- "/home/sci/visualruby/saski/src/Arayuz.rb"
- "/home/sci/visualruby/saski/src/Oyun.rb"
open_folders:
- "/home/sci/visualruby/saski"
- "/home/sci/visualruby/saski/src"
- "/home/sci/visualruby/saski/src/glade"
current_file: "/home/sci/visualruby/saski/src/Arayuz.rb"
current_line: 38
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
